### ISSUE TITLE
Setup style guide

### ISSUE THREAD

**Issue by Lakshmishri** [Netcentric/vg-volvotrucks-us-rd#1]
This task includes setting up style guide for the redesign work such as

1. Typography 
2. Colour Palate 

PS: After implementation, check how they look with existing design

**Comment by Andrei-Boiangiu** [comment]
testing was done using old and new pages as referece 
and pre-redesign screenshots for the VolvoTrucks Homepage have been documented in this wiki space for both the live site and the PR environment

[Volvo Trucks Homepage pre-redesign](https://projects.netcentric.biz/wiki/display/VOLVOFN/Volvo+Trucks+Homepage+pre-redesign)

[VolvoTrucks Homepage redesign](https://projects.netcentric.biz/wiki/display/VOLVOFN/VolvoTrucks+Homepage+redesign)

minor Bug opened above

closing this as Done
