### ISSUE TITLE
Lineup - Center aligned text Carousel Block variant

### ISSUE THREAD

**Issue by DanielaPedrochevd** [Netcentric/vg-volvotrucks-us-rd#100]
**Agile requirement**

As a User, I want to be able to navigate through the carousel blocked with the specified design in [Figma. ](https://www.figma.com/file/yv0VtHTvMoGPqkv0RAYcVp/PDP?type=design&node-id=7336-18330&mode=design&t=fIaA3zPeUi5ilQps-4)

**Description**

Create a new variant of the existing Carousel Block that has the text aligned to the center as the above-linked design. 

**Acceptance Criteria** 

1. There is a new variant of the Carousel Block in place that displays the texted aligned to the center and is available for content editors to use and add to a page.

**Comment by Andrei-Boiangiu** [comment]
confirmed as done 
as tested on https://100-truck-lineup-center-text--vg-volvotrucks-us-rd--netcentric.hlx.page/pdp
