### ISSUE TITLE
Content Task - Critical - None of the video players or video links play the videos

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [Netcentric/vg-volvotrucks-us-rd#101]
On the current main branch of VolvoTrucks, none of the video players or video buttons play the videos.

**Steps to reproduce:**
1. Go through the pages on https://main--vg-volvotrucks-us-redesign--netcentric.hlx.page/ and try to click on any video links and video buttons
2. Notice that none of the videos play when clicking on the links

**Expected result**
Videos links should be correctly functional and videos should play

**Actual result**
None of the videos on the VolvoTrucks redesign main branch play

**Comment by Andrei-Boiangiu** [comment]
@cogniSyb  this also occurs on https://main--vg-volvotrucks-us-rd--netcentric.hlx.page/ 
 
 see for examples the videos on this page
 https://main--vg-volvotrucks-us-rd--netcentric.hlx.page/trucks/vnr-electric/

**Comment by DanielaPedrochevd** [comment]
With the setup of the redesign project, some videos haven't been correctly copied (the media bots have not been setup) that's why this bug. @manuel-vara will take care of this for now.

**Comment by manuel-vara** [comment]
Franklin Bot configured for Redesign Slack channel. You can start using it to upload local videos to this site.

**Comment by manuel-vara** [comment]
Yes, if you want to have it same setup as preview & prod, but you can always keep using the absolute URL to prod media, as now. That's working: https://main--vg-volvotrucks-us-rd--netcentric.hlx.page/
As you said, it seems related with the fact the old url was used to test, so not sure what would be the issue here.

**Comment by DanielaPedrochevd** [comment]
This is a content task

**Comment by BeckyMedlin** [comment]
@Kannan-CM Are you actively working this ticket? Please add to sprint if it's being worked or update the status to reflect its status. Thank you!

**Comment by Kannan-CM** [comment]
Hi @manuel-vara @Andrei-Boiangiu ,
I see the videos are playing. Please let me know if there is still an issue?

**Comment by manuel-vara** [comment]
No, not from technical point of view.

**Comment by BeckyMedlin** [comment]
Closing as completed.
