### ISSUE TITLE
Refactor buttons

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-volvotrucks-us-rd#102]
Alignment of buttons is off in some places.

### Requirements
- ~Comply with code of Mack Trucks by using BEM structure~
- All buttons should have uppercase text
- Content should overflow on two lines when there’s not enough room #98 
- Hover state of buttons should respond to their environment ([when used in a card](https://github.com/Netcentric/vg-volvotrucks-us-rd/blob/main/blocks/v2-content-card/v2-content-card.css#L96))
- Make sure the colour of [a button on video component](https://88-teaser-cards--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/laura/) is right
- Fix the sizing of buttons when an icon is used:
![image (1)](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/133873665/414da8f5-e351-4007-a1fe-3892b36faee2)

**Comment by Andrei-Boiangiu** [comment]
confirmed as done
