### ISSUE TITLE
Space between last section and footer

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-volvotrucks-us-rd#108]
There’s whitespace between the last section and the footer.

Homepage:
<img width="1186" alt="Screenshot 2023-09-20 at 12 24 40" src="https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/133873665/10f42b70-477d-4fe1-95fb-f46cd05e4e58">

PDP:
![Screenshot 2023-09-20 at 14 25 32](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/133873665/a85a3d98-de51-42f3-b9b8-13ae8db08209)

**Comment by Andrei-Boiangiu** [comment]
confirmed as done with the current space of 48px between the items
