### ISSUE TITLE
Menu scrolled up on iOS after navigating back

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-volvotrucks-us-rd#121]
When I use the mobile menu on iOS, and I navigate to a page, and I use the browser back button, the menu is open and not completely visible.

It seems that the header has in this situation both the class `header--hidden` and `header--hamburger-open`

![IMG_0743](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/133873665/503f2055-a7ad-405f-874f-1c38f9b4aae8)

**Comment by DanielaPedrochevd** [comment]
@Andrei-Boiangiu can you provide an update?

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
