### ISSUE TITLE
Bug - Mobile view - Critical - The Custom modal does not disappear after selecting a link or by clicking the X button

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [Netcentric/vg-volvotrucks-us-rd#123]
When opening the Subnav and the custom modal pops up - after clicking a link from the custom modal the custom modal still stays present at the bottom of the scroll and neither clicking X will close it

**Steps to reproduce:**
01. Go to https://95-bug-inpagenavigation--vg-volvotrucks-us-rd--netcentric.hlx.page/pdp#powertrain and open in Mobile view
02. Click on the subnav and open the custom modal and click on one of the subnav sections
03. Scroll down and notice that the custom modal is still present and did not disappear upon clicking the link
04. Click on the X on the custom modal
05. Notice that the custom modal does not close

**Expected result**
Custom modal should disappear once a link is tapped or once the X is clicked

**Actual result**
Custom modal does not disappear once a link is tapped or once the X is clicked and it stays floating at the bottom of the page

**Comment by Andrei-Boiangiu** [comment]
#45

**Comment by kesiah** [comment]
Can you check https://develop--vg-volvotrucks-us-rd--netcentric.hlx.page/pdp#powertrain? Seems solved in develop.

**Comment by Andrei-Boiangiu** [comment]
I confirm that this issue does not occur on https://develop--vg-volvotrucks-us-rd--netcentric.hlx.page/pdp#powertrain
