### ISSUE TITLE
Bug - Major - Safari browser - Key Facts - Video thumbnail for Key Facts with video component is not correctly displayed on Safari

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [Netcentric/vg-volvotrucks-us-rd#125]
Video thumbnail from a Key Facts with video component is not correctly displayed on Safari browser

**Steps to reproduce:**
1. Open https://42-key-facts--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/tdziezyk/v2/key-facts on Safari browser and scroll down to Key Facts with Video component
2. Notice that the video thumbnail is not correctly displayed

**Expected result**
Video thumbnail should be correctly displayed

**Actual result**
Video thumbnail is not correctly displayed on Safari browser
<img width="1727" alt="image" src="https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/127409602/bb213b2e-e902-430d-8c80-7c59e4e81b23">

**Comment by Andrei-Boiangiu** [comment]
#42

**Comment by ZoeBeykirch** [comment]
Tagging @Joesturbo, @BeckyMedlin and @Kannan-CM - this seems like a good solution, what do you think?

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed as per the solution above
 and as tested on https://125-safari-key-facts-video--vg-volvotrucks-us-rd--netcentric.hlx.page/pdp
