### ISSUE TITLE
Deployment from Redesign Repos to Production (Volvo Only)

### ISSUE THREAD

**Issue by ZoeBeykirch** [Netcentric/vg-volvotrucks-us-rd#126]
We have defined the overall process of the deployment from Redesign repos to Prod here:
https://projects.netcentric.biz/wiki/display/VOLVOFN/Deployment+process+of+Production+ready+redesign+blocks

to summarise from the main document, the main ideas would be:
1. Netcentric will do QA smoke regression testing of the PR to be merged upstream and
2. Netcentric proposal to Volvo is to have an UAT testing and sign off step before merging the new functionality into production, this may require some content preparation upfront in some cases to ensure a specific page is ready for the new blocks.

Next Steps: 
1. Assess the importance of each of bugs found and they are blockers or not to go-live. :white_check_mark:
2. Those filtered in are the ones we would to estimate (high-level) effort. :white_check_mark:
3. Plan based on the priorities of those bugs (and, of course, taking into account the ongoing redesign backlog work priorities as well) :white_check_mark:
4. Execute the bug fixing step  ( 2d)
5. UAT testing (2d)

We would be targeting next Thursday (ideally 9/28) to sync up prod repos. We would like to confirm with you, header and footer updates to prod repos are fine.

**Comment by DanielaPedrochevd** [comment]
**Agile Requirement**
As a business owner, I want to approve the signed off code before going live. 

**Description**
Test the following URLs (QA and UAT) to sign them off: 

Also, test the header and footer prior to deployment. 

**Acceptance Criteria**

1. The above-mentioned urls and header and footer are tested and approved by business before they are merged to production.

**Comment by manuel-vara** [comment]
Above QA/UAT comment updated. FYI @Andrei-Boiangiu , @ZoeBeykirch , @BeckyMedlin , @Kannan-CM , 
@Joesturbo

**Comment by BeckyMedlin** [comment]
@manuel-vara @DanielaPedrochevd Should this be split into 2 stories - one for Volvo and one for Mack?

**Comment by Andrei-Boiangiu** [comment]
Posting here content ( or possible content) issues.

01. on Homepage https://develop--vg-volvotrucks-us-rd--netcentric.hlx.page/ 

Images from Trucks Lineup carousel are displayed as compressed on Mobile view

![image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/127409602/22d33e12-2eb9-4604-9756-3f0dcb4dcb07)

![image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/127409602/bb18066a-be6f-422f-a4fb-8b486bc9f020)

02. On Trucks -> VNL -> Exterior  https://develop--vg-volvotrucks-us-rd--netcentric.hlx.page/trucks/vnl/exterior/ 

Video does not play

<img width="1677" alt="image" src="https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/127409602/bdf35f9b-75ea-46e6-bb03-221d353e447d">

**Comment by ZoeBeykirch** [comment]
Footer needs to be updated before pushing to production for small content text change - reference  https://github.com/Netcentric/vg-volvotrucks-us-rd/issues/145

**Comment by Andrei-Boiangiu** [comment]
> 1. https://develop--vg-volvotrucks-us-rd--netcentric.hlx.page/

confirmed as fixed

**Comment by Andrei-Boiangiu** [comment]
additional possible content issue for PDP page

https://develop--vg-volvotrucks-us-rd--netcentric.hlx.page/pdp

on the Trucks Lineup Carousel, the first three Truck images are displayed as stretched and not aligned when compared to the last two trucks

<img width="1805" alt="image" src="https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/127409602/f9a83be0-14ef-4f50-8b91-a245e5906bc8">

<img width="1805" alt="image" src="https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/127409602/93a11996-edda-4952-b37e-2cd24420108f">

**Comment by DanielaPedrochevd** [comment]
On hold until we get the images we need to fix the content issue reported in the previous comments.

**Comment by BeckyMedlin** [comment]
@Kannan-CM Have the content issues noted in this ticket been resolved yet?

**Comment by Kannan-CM** [comment]
Hi @BeckyMedlin ,
belileve the new images fixed the issue.
