### ISSUE TITLE
Masonry grid

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-volvotrucks-us-rd#13]
A masonry grid containing images. Instead of images, videos can be used as well.

The following image sizes are being used:
- square
- big square (2×2)
- portrait (2×3)
- landscape (2×1)
- big landscape (full width, different aspect ratio of around 16:9)

The images follow a specific order:
1. big landscape
2. square
3. square
4. big square
5. landscape
6. portrait
7. square
8. square

On mobile, two square images can be placed next to each other
The grid has a gap of 16px on mobile and tablet, 32px on desktop

On tablet and desktop, the images will be placed in the same masonry grid. Schematically it could work like this:
```
grid-template-areas: 
    "big-landscape big-landscape big-landscape big-landscape"
    "big-landscape big-landscape big-landscape big-landscape"
    "big-landscape big-landscape big-landscape big-landscape"
    "big-square    big-square    square1       square2"
    "big-square    big-square    portrait      portrait"
    "square3       square4       portrait      portrait"
    "landscape     landscape     portrait      portrait";
```

![grid-mobile](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/133873665/b9d6613e-338f-4013-974d-ac2e81c21e85)
![grid-tablet](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/133873665/43c58f20-ccfc-42d3-89f8-934310f7e5a6)
![grid-desktop](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/133873665/62a64d85-3387-4a43-abbb-15b51bfc7881)

The [design files provided](https://www.figma.com/file/yv0VtHTvMoGPqkv0RAYcVp/PDP?type=design&node-id=1929-25366&mode=dev) show a variant of order on tablet/desktop. This is the one with the black background, for interior. For now the different order is out of scope.

**Comment by kesiah** [comment]
Please, could you provide a screenshot of the block? Also, figma link :)

**Comment by kesiah** [comment]
Question: as videos can be used, will they be autoplayed? If yes, what happens with AA? If no, do we need to include play button? Which design?

**Comment by Andrei-Boiangiu** [comment]
confirmed as tested and fixed as according to the description
