### ISSUE TITLE
Bug - Major: new Volvo header has too much white padding under

### ISSUE THREAD

**Issue by ZoeBeykirch** [Netcentric/vg-volvotrucks-us-rd#147]
The white space padding under the new Volvo header navigation needs to be decreased to match what is in the Figma designs below:

Figma: https://www.figma.com/file/IcqreRKnNYyDVMc28yoOeh/Homepage?type=design&node-id=4152%3A4030&mode=design&t=KHgv6jEXwKNbcTMB-1

Desired Request: 

![Image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/125895595/a334de81-201c-4ea0-8d3e-a517a0da39d5)

Current Website: 

![Image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/125895595/6dc2f429-b84f-4316-969f-13b73bff68a5)

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
as tested on https://147-header-block-whitespace--vg-volvotrucks-us-rd--netcentric.hlx.page/our-difference/
