### ISSUE TITLE
Bug - Major: On Volvo "Trucks" navigation mega menu tab the truck images don't link to the pages

### ISSUE THREAD

**Issue by ZoeBeykirch** [Netcentric/vg-volvotrucks-us-rd#148]
On Volvo "Trucks" navigation mega menu tab the truck images don't link to the pages. Right now the user must have to click on the text title underneath the images. This requires a fix to restore the previous version feature that allowed for users to click the truck image to take them to the appropriate CTA page. 

![Image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/125895595/74d54681-e6e9-4c87-b10a-22442277c2ec)

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed 
 as tested on https://128-redesign-mega-dropdown--vg-volvotrucks-us-rd--netcentric.hlx.page/pdp

**Comment by ZoeBeykirch** [comment]
Just took a look and seems to be resolved in pre-production, but this issue still persists on the live site. Can we wait to close tickets until the bug has been fixed in the live website? Or is this documented/accounted for in another way?

**Comment by DanielaPedrochevd** [comment]
The team discussed this and the procedure is that once the bug is tested and fixed in pre-production, which is the case for this one, the bug can be marked done.

**Comment by Andrei-Boiangiu** [comment]
closing as per above comment
