### ISSUE TITLE
Trucks lineup carousel

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-volvotrucks-us-rd#16]
Related to #36 

Restyling of the block [tabbed carousel](https://www.volvotrucks.us/trucks/vnr-electric/#meet-the-vnr-family). It should be a fork/new block, as we’re not using the same structure for every occurance of this block. The code of this block will also be used for Mack Trucks.

- First truck enter when component comes in view
- Clicking a tab would navigate in the trucks accordingly
- Different images are used on Tablet/Mobile (trucks are front facing)

When the tabs won’t fit, we can scroll through them (overflow: auto)

### Content
The section should start with an H2 (now displayed as H4 or H3)

Every slide/truck will have its own content:
- Product name (displayed inline with text)
- Text
- Explore button links to its respective PDP
- Build yours button links to an external URL and can be shown optionally

On the PDP, the section and block will be displayed differently:
- Text below heading
- Different button type, which links to Truck Builder
- Link with + icon (to a modal window?)

### Design
The [item on Figma](https://www.figma.com/file/IcqreRKnNYyDVMc28yoOeh/Homepage?type=design&node-id=1387-17455&mode=dev) is shown on the homepage.

On the PDP, we show instead of the different truck series, the models within the series.

#### Out of scope
- Animation of moving truck on scroll
- Animation of rolling tyres

**Comment by Andrei-Boiangiu** [comment]
putting back In Progress for two Major bugs:
 
 [Bug - Major - Trucks Lineup Carousel - Explore button is incorrectly displayed or missing on some of the Trucks from the carousel #51](https://github.com/Netcentric/vg-volvotrucks-us-rd/issues/51)
 
 [Bug - Major - Mobile view - Trucks Lineup Carousel - Slides from the Trucks Carousel do not have different (front facing) images displayed on the Mobile view #52](https://github.com/Netcentric/vg-volvotrucks-us-rd/issues/52)
 
 #51 #52

**Comment by Andrei-Boiangiu** [comment]
confirmed as done
