### ISSUE TITLE
Bug: High - Truck carousel tabs display a blue border when selected

### ISSUE THREAD

**Issue by ZoeBeykirch** [Netcentric/vg-volvotrucks-us-rd#160]
When the user selects a tab from the Our Truck Lineup on the home page, and blue border appears around the selected tab. The blue border will remain highlighted until the user clicks something else on the page. The expected behavior is for only the tabs to be underlined when they are selected. 

![Image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/125895595/2c5ff0a5-45c5-478d-ae00-abfa5c90d06a)

**Comment by ZoeBeykirch** [comment]
Thanks for this explanation, Syb! Tagging @williebender for awareness

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed 
 as tested on https://develop--vg-volvotrucks-us-rd--netcentric.hlx.page/
