### ISSUE TITLE
Bug: Medium - Truck lineup carousel tab first underlines VAH, when it should underline VNL

### ISSUE THREAD

**Issue by ZoeBeykirch** [Netcentric/vg-volvotrucks-us-rd#165]
On the truck lineup carousel block, when the user first views the page the VAH tab at the very right is underlined, when the expected behavior should have the VNL tab underlined as that is the first truck on the lineup that is presented in the carousel images.   

(https://develop--vg-volvotrucks-us-rd--netcentric.hlx.page/)

![Image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/125895595/a6874e36-b3e3-46e3-9d45-6787f53fc192)

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed as tested on https://165-incorrect-active-state--vg-volvotrucks-us-rd--netcentric.hlx.page/
