### ISSUE TITLE
Deploy new Volvo Header and footer to the Canadian market websites

### ISSUE THREAD

**Issue by ZoeBeykirch** [Netcentric/vg-volvotrucks-us-rd#169]
Deploy the new Volvo header and footer to the Canadian Volvo websites: 

https://www.volvotrucks.ca/en-ca/
https://www.volvotrucks.ca/fr-ca/

Acceptance Criteria: 
- French Canadian Volvo website header and footer should be translated to French to match the current header/footer on live website.
- The Country / Region CTA on the Footer (currently reads USA) should be changed to "CAN"

**Comment by DanielaPedrochevd** [comment]
**Agile requirement**
As a business owner, I want https://www.volvotrucks.ca/en-ca/
https://www.volvotrucks.ca/fr-ca/ to display the correct header and footer (the one currently in production) to align with the rest of the deployed pages. 

**Description**
Do a deployment from prod to https://www.volvotrucks.ca/en-ca/
https://www.volvotrucks.ca/fr-ca/ of the header and footer, and test. The only thing that should differ from the production project is the config files. 

**Acceptance Criteria**
1. The new header and footer is available in https://www.volvotrucks.ca/en-ca/
https://www.volvotrucks.ca/fr-ca/

**Comment by DanielaPedrochevd** [comment]
Translations to French have to be done but this is a content issue so not part of our development.

**Comment by BeckyMedlin** [comment]
@Kannan-CM  This can be handled after the new header and footer are released.

**Comment by BeckyMedlin** [comment]
@Gonzalo-CG and @DanielaPedrochevd The header and footer needs to be pushed all at once together. No need to wait on this item.

**Comment by BeckyMedlin** [comment]
Closing -- this work needs to be handled in Franklin (production) ticket https://github.com/hlxsites/vg-volvotrucks-ca/issues/50

**Comment by ZoeBeykirch** [comment]
This work will be picked up in https://github.com/hlxsites/vg-volvotrucks-ca/issues/50
