### ISSUE TITLE
Bug: Medium - Stories Carousel displaying 2 instead of 3 articles

### ISSUE THREAD

**Issue by ZoeBeykirch** [Netcentric/vg-volvotrucks-us-rd#170]
The Stories Carousel block should display 3 article stories when the user first loads the homepage, and currently the user can only view 2 articles as a carousel starting position as seen below. 

Current Outcome: 

![Image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/125895595/ce63e234-a67e-421c-b3ed-dfaba31d352b)

Desired Outcome: 

![Image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/125895595/0b194d06-a4f0-47cd-bf17-aafee18104f7)

**Comment by DanielaPedrochevd** [comment]
This is a bug, figma states 2nd item in the carousel should be on focus. 
<img width="283" alt="Captura de pantalla 2023-10-19 a las 12 53 44" src="https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/144998505/546ba43c-782d-4980-ac8c-46685c53d970">

**Comment by Andrei-Boiangiu** [comment]
second item of the carousel is currently in Focus
  
  
<img width="1825" alt="image" src="https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/127409602/adfdb9e2-18f8-4e4f-8d38-8a7c959bca49">

confirmed as fixed 
as tested on the URL above
