### ISSUE TITLE
Bug - Minor - PDP - Hero not fully in view

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-volvotrucks-us-rd#175]
The hero should be always 100% of the viewport height minus the header. On the PDP we use the inpage navigation.

The height of the inpage navigation block needs to be removed from the height of the hero. This way the pause button #156 and scroll indicator remain in view.

Expected:
<img src="https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/133873665/63381523-4601-4f92-8e92-77548e5b08ff" width="375">

Result:
<img src="https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/133873665/aa1ed9de-ca2b-43f6-be03-803598e29709" width="375">

**Comment by DanielaPedrochevd** [comment]
@TomaszDziezykNetcentric please approve this

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
 as tested on https://175-hero-not-fully-in-view--vg-volvotrucks-us-rd--netcentric.hlx.page/pdp

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed as tested on Safari and on iPhone 13 and Ipad 10 (browserstack)
