### ISSUE TITLE
Bug - Minor - Footer toggle icon too small

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-volvotrucks-us-rd#176]
For the mobile menu, we’re following the Core Design Kit. The chevron icons are smaller in the footer (16px).

Confirmed with agency: "change the chevrons to 24px in the footer so it is consistent with the kit and matches the menu"

Expected:
<img src="https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/133873665/4deddcce-4162-467f-b398-70f8db8f25cc" width="375">

Result:
<img src="https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/133873665/f7fa6e35-cc67-4ba3-af8e-33fe27d87603" width="375">

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
 as tested on https://176-footer-toggle-size--vg-volvotrucks-us-rd--netcentric.hlx.page/
