### ISSUE TITLE
FR: Volvo Trucks Video Module Block New Variant

### ISSUE THREAD

**Issue by DanielaPedrochevd** [Netcentric/vg-volvotrucks-us-rd#178]
**Agile Requirement** 
As a business owner, I want to display videos on pages where they occupy the whole width of the page [as in the design ](https://www.figma.com/file/yv0VtHTvMoGPqkv0RAYcVp/PDP?type=design&node-id=7369-10472&mode=design&t=ZPrXUdQRUIIO3ABZ-4) without the hover effect the current video v2 block has. 

So that users can interact with said video. 

**Description**
Create a new variant for the video block so that editors can add videos to a page and these occupy the whole page without a hover effect. 

**Acceptance Criteria**

1. The Video Block has a new variant that is like the video block v2 current state but without the hover and animation effect.

**Comment by DanielaPedrochevd** [comment]
related to #182

**Comment by Joesturbo** [comment]
@DanielaPedrochevd  isn't this ticket really to modify this module?
Make it smaller and add pause button?

If we can it should reduce the time down to almost nothing.

https://www.volvotrucks.us/trucks/powertrain/i-torque/

**Comment by Andrei-Boiangiu** [comment]
confirmed as done
 as tested on https://178-v2-video-block-variant--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/syb/video
