### ISSUE TITLE
Video component

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-volvotrucks-us-rd#18]
Autoplay video content, full width. Overlaid is a title, text, and a link.

The video is [masked](https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape/inset), with rounded corners. On desktop, the video is shown smaller, as wide as the content container. The mask will expand to full width on scroll/hover.

- On all device classes, the unmasked video will be as big as the viewport
- On mobile and tablet, overlaid content is aligned vertically to the bottom, horizontally centred
- On tablet, the overlaid content has a maximum width
- On desktop, overlaid content is aligned vertically centred, horizontally left

On PDP we can use this block as well. Here it can be [used without overlaid content](https://www.figma.com/file/yv0VtHTvMoGPqkv0RAYcVp/PDP?type=design&node-id=2877-39063&mode=design&t=Z1SLCcUpjFiApVj3-4).

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed as per the points above
