### ISSUE TITLE
FR: Volvo Trucks Magazine Footer

### ISSUE THREAD

**Issue by DanielaPedrochevd** [Netcentric/vg-volvotrucks-us-rd#190]
**Agile Requirement**
As a business owner, I want my site to have a footer to display specific content and links in all the pages. 

https://www.figma.com/file/SDLKNiRf0s5Jbhqn9TJZ6H/Magazine?type=design&node-id=446-14332&mode=design&t=r6mxfCT8zuQckpuW-4

**Comment by BeckyMedlin** [comment]
@DanielaPedrochevd We need to reuse the footer that exists on the site. Closing as a duplicate.
