### ISSUE TITLE
FR: Volvo Trucks Magazine Subscription Bar

### ISSUE THREAD

**Issue by DanielaPedrochevd** [Netcentric/vg-volvotrucks-us-rd#191]
**Agile Requirement**
As a business owner, I want users to be able to subscribe to the magazine so that they can receive the latest updates from Volvo. 

https://www.figma.com/file/SDLKNiRf0s5Jbhqn9TJZ6H/Magazine?type=design&node-id=446-14332&mode=design&t=r6mxfCT8zuQckpuW-4

### Description
A block used to allow users to subscribe to a newsletter will be developed. This block will be used on [#211 - Template: Magazine Article](https://github.com/Netcentric/vg-volvotrucks-us-rd/issues/211) but can be used outside of the template, as a stand-alone block (e.g. on the Magazine Page).

![image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/139977780/d1449759-6000-498c-b83c-624786cc72f1)

**Comment by BeckyMedlin** [comment]
@DanielaPedrochevd Per discussion with @williebender, we need to reuse the subscription form on the homepage. No need to create a new one. Closing as duplicate.
