### ISSUE TITLE
Bug:  Volvo Trucks Regression issues

### ISSUE THREAD

**Issue by DanielaPedrochevd** [Netcentric/vg-volvotrucks-us-rd#196]
**How to reproduce**

1. Go to the Volvo Home Page. 
2. Check the footer.
3. Navigate to a different page (e.g. any PDP). 
4. Check the footer.  

**Expected Result**

The footer looks the same in all pages. 

**Actual Result**

The labels from the footer in pages that are not the Home Page are in a smaller size and the text in the bottom of the footer also looks off. 

![Image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/144998505/92caa3f8-957d-4b89-aa16-94631016ca74)

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
 as tested on https://release-2--vg-volvotrucks-us-rd--netcentric.hlx.page/pdp
