### ISSUE TITLE
FR: Volvo Trucks Configurator Embed to website

### ISSUE THREAD

**Issue by ZoeBeykirch** [Netcentric/vg-volvotrucks-us-rd#199]
Oct 11th: We still have some minor tweaks before we can provide an example for the embedding of VTNA, but attached is a similar file to use for testing - a pure html file with a few lines. This shows what you need to add to the page where you want the configurator to live.

It will look almost identical to how we already are doing it for VTG (global) - https://www.volvotrucks.co.uk/en-gb/tools/truck-builder.html#/en-gb

Nov 13th: 
Below the zip file contains the build of the configurator for you to test with. It includes an HTML file which you can use as reference for how to link to the files. The configurator will render into an element with the id #configurator. It relies on its parent having a height of 100% so that it fits the full viewport.

Right now, there are a handful of CSS classes which are defined in the global scope – let me know if this causes styling conflicts on the development and Rapid Images team will try to scope them. If there’s any questions let’s take a short call.

[VTNA Configurator.zip](https://github.com/Netcentric/vg-volvotrucks-us-rd/files/13336254/VTNA.Configurator.zip)

**Comment by BeckyMedlin** [comment]
@manuel-vara Please share discovery for Volvo Group's solution for their configurator. We'd like to repurpose the same code in a component block.

**Comment by BeckyMedlin** [comment]
@manuel-vara Please go back to the global AEM team and repurpose what's being done for Volvo Trucks in EU with Configurator. Please advise next steps.

**Comment by manuel-vara** [comment]
We will need to create a custom block enabling js framework apps.
FYI @cogniSyb

**Comment by DanielaPedrochevd** [comment]
**Agile Requirement**
As a user, I want to configure a truck to my liking to see how it would look before making the purchase. 

**Description**
Create a new custom block called "Truck Configurator" that allows editors to add a route to the HTML in a JS Framework (React/Angular) developed app page. 

**Acceptance Criteria**

**Comment by DanielaPedrochevd** [comment]
Communication throughout the sprint will be needed with the application development agency (Rapid Images) to make design adjustments.

**Comment by Andrei-Boiangiu** [comment]
Reopening and sending back to In Progress due to the two Major bugs logged
 
Bug - Major - iPhone - Volvo Truck Configurator - X close window button is out of view in the Compare models pop-up
 https://github.com/Netcentric/vg-volvotrucks-us-rd/issues/311
 
 Bug - Major - Mobile - Volvo Trucks Configurator - User is not able to scroll down in landscape view #312
 https://github.com/Netcentric/vg-volvotrucks-us-rd/issues/312

**Comment by Andrei-Boiangiu** [comment]
confirmed as done as per the two bugs above
