### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Lakshmishri** [Netcentric/vg-volvotrucks-us-rd#2]
Implement new footer based on the design for all screen size
<img width="730" alt="Screenshot 2023-07-21 at 14 54 46" src="https://github.com/Netcentric/vg-volvotrucks-us-redesign/assets/4208604/2c537ae8-fbea-494b-9d84-f1dadde8623b">

https://www.figma.com/file/IcqreRKnNYyDVMc28yoOeh/Homepage?type=design&node-id=2-17&mode=design&t=m6ZmJZOL32SfzOzs-0

**Comment by ZoeBeykirch** [comment]
Minor changes coming to bottom links in footer - waiting for final approval on brand teams coming soon

**Comment by Lakshmishri** [comment]
Minor changes add in the [issue](https://github.com/Netcentric/vg-volvotrucks-us-rd/issues/50) so closing this
