### ISSUE TITLE
Bug - Minor - motion of header and inpage navigation inconsistent

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-volvotrucks-us-rd#203]
Due to recent changes, the timing of the header and inpage navigation became different. Both should be using the project-defined timing.

https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/133873665/f5e69999-35cd-4ac0-bf25-d9cf809b2c5f

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed 
as tested on https://203-navigation-motion--vg-volvotrucks-us-rd--netcentric.hlx.page/pdp
