### ISSUE TITLE
Bug - Major - button text in Firefox not wrapping

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-volvotrucks-us-rd#204]
The fix for #98 didn’t apply to Firefox.

Chrome:
<img src="https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/133873665/f7f4aae5-090e-4643-90d2-94240384cb2d" width="375">

Firefox:
<img src="https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/133873665/bdc90460-1b20-4453-ac2c-bcb36c1a1c9b" width="375">

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed 
as tested on https://204-button-wrap-in-fx--vg-volvotrucks-us-rd--netcentric.hlx.page/pdp
