### ISSUE TITLE
Bug - Critical - Mobile - iPhone - Video components are not working

### ISSUE THREAD

**Issue by ZoeBeykirch** [Netcentric/vg-volvotrucks-us-rd#206]
On the new page that uses the newly designed blocks the video components are not loading on mobile for iPhone users: https://www.volvotrucks.us/innovation/supertruck2/
 
Tested with iPhone users - issue is happening on Safari and Chrome browsers with devices: iPhone 13 iOS version 16.6.1 / iPhone 13 16.5.1(c) / iPhone X 16.1.1

Seems to work fine on Android devices - tested with Samsung A34 and Samsung 20FE and these components worked as expected. 

Bug Description:
The card blocks have an animated video for that is only showing a grey blank box for: 20% aero improvement, 50% aero improvement and Freight efficiency titles (see screenshots). Additionally, the blocks are supposed to be animated and are only showing images for the same blocks below for: Design and Engineering. 

![Image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/125895595/17a7b4e7-64d5-4fb1-8e98-684341c97fd0)
![Image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/125895595/6645e165-055f-4c56-acf3-3004f219e4b3)
![Image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/125895595/d65ff6eb-df76-49e5-8587-e1ef54dc7117)
![Image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/125895595/c1a1d85b-05c3-489e-b955-2e38706ffaac)

**Comment by ZoeBeykirch** [comment]
Sounds good! I will write another ticket for the Youtube video player and sounds great to plan to roll out a hotfix for autoplay iOS tomorrow. Thanks for the quick response!

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed as tested on iPhone 13 (browserstack)
 and on https://206-iphone-video--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/syb/teaser-cards
