### ISSUE TITLE
Bug - Major - Mobile - iPhone - Embed Youtube video player not loading as expected after accepting cookies

### ISSUE THREAD

**Issue by ZoeBeykirch** [Netcentric/vg-volvotrucks-us-rd#207]
For iPhone users on mobile, the embed video block using Youtube player is not loading as expected after the user accepts all cookies. After I accepted all cookies, I see a message over the blank video player - "For a premium high resolution experience, please accept cookies" with the screen shot for reference. Only once I refreshed my browser after accepting the cookies did the video player work as expected. Possibly a bug with the Youtube player, or maybe with OneTrust cookies? Is there another video block we can use to replace this? 

SuperTruck 2 page: https://www.volvotrucks.us/innovation/supertruck2/

Tested with iPhone users - issue is happening on Safari and Chrome browsers with devices: iPhone 13 iOS version 16.6.1 / iPhone 13 16.5.1(c) / iPhone X 16.1.1

Seems to work fine on Android devices - tested with Samsung A34 and Samsung 20FE and these components worked as expected.

![Image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/125895595/f7af61c9-ca8e-469a-9dc8-f9f81a08fda3)

**Comment by Andrei-Boiangiu** [comment]
I cannot reproduce this as per above

after accepting cookies I see the correctly embedded video and dont see the "please accept cookies prompt"

but when not accepting cookies the prompt is indeed displayed and the embedded youtube video is displayed as blank with the play button 

<img width="295" alt="image" src="https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/127409602/35b422f2-a9a1-41ba-8dd7-2ce60f3c28d6">

as tested on browserstack: iPhone 13

**Comment by Andrei-Boiangiu** [comment]
sure. I will leave here a screen recording of this issue as tested on browserstack: iPhone 13 Pro 
(sorry for the slow scroll down)


https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/127409602/50bdff61-cd2c-4eea-9ca8-6b72a57ab118

**Comment by ZoeBeykirch** [comment]
@Andrei-Boiangiu I sent you the video via slack, it was too large to upload here

**Comment by Andrei-Boiangiu** [comment]
update on this:
 I confirm via Zoe's video that this issue does indeed occur on an actual iPhone 13 device (not browserstack)
 
 but it does reproduce on an actual iPhone 12 device as verified by @cogniSyb 
 
 to be investigated and updated

**Comment by Kannan-CM** [comment]
Will contact our OneTrust support team and request them to investigate into it.

**Comment by Kannan-CM** [comment]
Hi Syb,

We investigated the Iphone issue and found that the Iphone is not getting refreshed after the cookie is accepted.

Which is not the case with Mack trucks. On the same Iphone device, when we accept the cookies the page refreshes and the cookies status is updated.

Could you please see if you can force the page to reload on Iphone, after the cookie button is clicked?

**Comment by Kannan-CM** [comment]
* Category Name
Performance Cookies
* Category Id
C0002
* Description
These cookies allow us to count visits and traffic sources so we can measure and improve the performance of our site. They help us to know which pages are the most and least popular and see how visitors move around the site. All information these cookies collect is aggregated and therefore anonymous. If you do not allow these cookies we will not know when you have visited our site, and will not be able to monitor its performance.

**Comment by Kannan-CM** [comment]
* Category Name
Functional Cookies
* Category Id
C0003
* Description
These cookies enable the website to provide enhanced functionality and personalisation. They may be set by us or by third party providers whose services we have added to our pages. If you do not allow these cookies then some or all of these services may not function properly.

**Comment by Kannan-CM** [comment]
* Category Name
Targeting Cookies
* Category Id
C0004
* Description
These cookies may be set through our site by our advertising partners. They may be used by those companies to build a profile of your interests and show you relevant adverts on other sites. They do not store directly personal information, but are based on uniquely identifying your browser and internet device. If you do not allow these cookies, you will experience less targeted advertising.

**Comment by ZoeBeykirch** [comment]
Re-tested and validated that the issue has been resolved!
