### ISSUE TITLE
Bug - Medium - Truck Carousel should always begin with VNL

### ISSUE THREAD

**Issue by ZoeBeykirch** [Netcentric/vg-volvotrucks-us-rd#217]
For the Truck Carousel block on the [redesign homepage ](https://main--vg-volvotrucks-us--hlxsites.hlx.page/homepage-v2), when the user first views the page the VNL should be the first truck model the user sees on the carousel. Currently the motion is random what truck it lands on, sometimes the user first sees VHD, VNX or VAH. As seen in the screen shot below, the user first sees the VNX truck model, which should be corrected to the first VNL model. 

![Image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/125895595/fc0ad9b0-b349-49c5-8231-502bd9541461)

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed as per above
