### ISSUE TITLE
Bug - Medium - Truck Carousel Tablet View Issues

### ISSUE THREAD

**Issue by ZoeBeykirch** [Netcentric/vg-volvotrucks-us-rd#219]
For the Truck Carousel block on the [redesign homepage](https://main--vg-volvotrucks-us--hlxsites.hlx.page/homepage-v2), the tablet view we are seeing some odd text bugs and movement when swiping between models - see attached. 

Current Result: 

![Image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/125895595/b010978d-a8dd-4440-a6d1-dbc7dede6aea)

Desired Result: 

https://www.figma.com/file/IcqreRKnNYyDVMc28yoOeh/Homepage?type=design&node-id=5776%3A21617&mode=design&t=fALkGE8qdsY1nxmU-1

**Comment by DanielaPedrochevd** [comment]
confirmed as bug

**Comment by ZoeBeykirch** [comment]
I will check with Saamia who did the testing on this one. CCing @csulitzer for awareness

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
