### ISSUE TITLE
Bug - Minor - Truck Carousel text box width adjustment

### ISSUE THREAD

**Issue by ZoeBeykirch** [Netcentric/vg-volvotrucks-us-rd#221]
For the Truck Carousel block on the [redesign homepage](https://main--vg-volvotrucks-us--hlxsites.hlx.page/homepage-v2), the truck description text box width is currently 341 pixels x 59 pixels. Figma is 567 pixels x 80 pixels (dimensions do not match for tablet and mobile as well)

Current Result: https://www.figma.com/file/IcqreRKnNYyDVMc28yoOeh/Homepage?type=design&node-id=5775%3A21321&mode=dev

Desired Result: https://www.figma.com/file/IcqreRKnNYyDVMc28yoOeh/Homepage?type=design&node-id=4259%3A4276&mode=dev

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed as per above changes
 and as tested on https://221-truck-lineup-textbox--vg-volvotrucks-us-rd--netcentric.hlx.page/
