### ISSUE TITLE
Bug - Major - Microsoft Edge Browser issues rendering 'stories on the road' block

### ISSUE THREAD

**Issue by ZoeBeykirch** [Netcentric/vg-volvotrucks-us-rd#227]
For the 'Stories on the road; block on the [redesign homepage](https://main--vg-volvotrucks-us--hlxsites.hlx.page/homepage-v2), in the Edge browser on desktop computers the block title/description/CTA under the carousel seems to be having issues displaying the text. When the user scrolls, it is primary whites space and the text will pop up randomly when scrolling (I took a video recording but cannot attach it to the ticket - Happy to email this example if there are any questions).
Also, the buttons to scroll through the carousel don't always work when clicking on the arrows, only using the tabbed key on the keyboard will make it work 100%. 

![Image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/125895595/aeca9d20-56bd-48ca-b794-fbcb3ea73e32)

**Comment by DanielaPedrochevd** [comment]
This is a change request, will be handled in ticket #78

**Comment by ZoeBeykirch** [comment]
The block looks different, but the title/descriptions still aren't showing as expected and tabs don't work to click through the carousel. This bug is now only happening on desktop - on mobile in Edge it looks fine. I'll have some other users test it today as well to see if anyone else can re-produce it. 
![image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/125895595/f37a9ab6-a2f4-4955-9a39-4ffdd8cef373)

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed as tested on Microsoft Edge on Windows (on browserstack)
  as well as Chrome and Safari on MacOS
  
  
<img width="1530" alt="image" src="https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/127409602/b7f50de4-0d66-4b20-a845-f3f6ead4373f">
