### ISSUE TITLE
Bug - Minor - unwanted rounded corner in content card

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-volvotrucks-us-rd#228]
Content card type 1 in wide state has an incorrect rounded corner in the bottom right. This should be only the case for type 2 and 3. See https://www.volvotrucks.us/innovation/supertruck2/

<img width="1205" alt="Screenshot 2023-10-18 at 09 35 19" src="https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/133873665/5049b69a-3038-46f8-8417-7a205f20186b">

**Comment by Andrei-Boiangiu** [comment]
this still has rounded corner on these content card types here 
 on https://228-rounded-corner--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/syb/teaser-cards
 
 
<img width="1781" alt="image" src="https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/127409602/3d7e2376-6255-494d-aff7-0823baab2daf">

**Comment by Andrei-Boiangiu** [comment]
closing as per above comment
