### ISSUE TITLE
Subscribe to newsletter form response

### ISSUE THREAD

**Issue by manuel-vara** [Netcentric/vg-volvotrucks-us-rd#245]
Get success/error response back from Pardot Form Handler.
Linked to #96 and its comments history.

**Comment by BeckyMedlin** [comment]
@williebender Please provide "standard" response message for success and error.

**Comment by Andrei-Boiangiu** [comment]
confirmed as done
 as tested on https://245-subs-form-response--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/manuel.vara/homepage-test
