### ISSUE TITLE
Bug: Major: form subscribe confirmation message is not rendering as expected

### ISSUE THREAD

**Issue by ZoeBeykirch** [Netcentric/vg-volvotrucks-us-rd#249]
Link:
https://www.volvotrucks.us/

Browser: Chrome

Steps to reproduce:
On the new Subscribe block on the bottom of the homepage, submit your email address and the confirmation message brings users to another page - https://245-subs-form-response--vg-volvotrucks-us-rd--netcentric.hlx.page/blocks/pardot-form/responses/success.js

Expected behavior
The confirmation message for subscribe should not bring users to another page, there should be a message that looks like the following 

![Image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/125895595/86b02534-021a-4de6-beb3-21ba152bcc1f)

Actual behavior
The confirmation message is not rendering as seen below

![Image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/125895595/577dd8ce-9c1e-476d-8376-300600d58ced)

**Comment by manuel-vara** [comment]
Will be fixed by #245

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed by #245
