### ISSUE TITLE
Bug - Major - Content carousel visual issues

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-volvotrucks-us-rd#258]
Multiple instances of the block on a page break the disable functionality for previous/next buttons. The first instance will work fine, the following instances of the block won’t disable the buttons at either end of the carousel.
![Screenshot 2023-11-20 at 09 28 46](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/133873665/f622ef77-4c6f-4e94-abce-15d86a077fa6)

Block misses specific styling for gradient on gray and black background:
![Screen Shot 2023-11-20 at 09 26 49](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/133873665/cca78980-2a2e-4df5-be4c-9bd0ce2994e9)
![Screen Shot 2023-11-20 at 09 26 32](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/133873665/dc08016e-44a1-41b5-8bea-52c3538943d9)

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
 as tested on https://258-carousel-fixes--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/lakshmi/content-carousel
