### ISSUE TITLE
Bug: Major: Inpage navigation is in reversed order on Firefox

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-volvotrucks-us-rd#262]
The buttons of the Inpage navigation (#45) are reversed on Firefox. Chrome and Safari display it correctly.

Expected:
![Screen Shot 2023-11-21 at 20 25 19](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/133873665/cd596e09-793e-4cd4-8803-8fab330b2361)

Result:
![Screen Shot 2023-11-21 at 20 25 43](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/133873665/aebcfbcd-258f-4249-9c93-0a662b617a28)

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed 
  as tested https://262-inpage-nav-reversed--vg-volvotrucks-us-rd--netcentric.hlx.page/pdp
