### ISSUE TITLE
Bug: Minor - Media Gallery missing rounded corners

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-volvotrucks-us-rd#272]
Rounded corners are missing. Apparently the current demo contains exported images with rounded corners (transparent background).

![Image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/133873665/0ea94a1c-25a4-451b-bf41-ca33b51e3bf8)
![Image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/133873665/3811e560-5b5f-42dd-bc7e-e2d2d4b51929)

Further refactoring:
- Block is now called `v2-text-with-images` and should be renamed to `media-gallery`
- Sizes to be updated
  - `.v2-text-with-images__col` should have `max-width` set with `var(--text-block-max-width)`, replacing 500px/700px
  - Gap between items should be 16px on mobile and tablet
  - Gap between items should be 32px on desktop
  - On desktop, the text block should be having a size of `21rem`

**Comment by Andrei-Boiangiu** [comment]
confirmed as done
 as tested on https://272-media-gallery--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/tdziezyk/v2/textual-content-with-images
 
 and additionally for rounded corners on 
 https://272-media-gallery--vg-volvotrucks-us-rd--netcentric.hlx.page/
 https://272-media-gallery--vg-volvotrucks-us-rd--netcentric.hlx.page/pdp
