### ISSUE TITLE
Bug - Stories from the road (stories carousel) - Issue in viewport > 2000px

### ISSUE THREAD

**Issue by kesiah** [Netcentric/vg-volvotrucks-us-rd#28]
I tested the carousel on a desktop (with a high-resolution 2500px+) and I found a weird behavior. I suspect that's because more than one slide can be active at the same time.
Steps to reproduce:
1. Load the page on the 2500px + device
2. Click the right button -> Slide switch to the second item
3. Click the right button -> not working - nothing happened

_Originally posted by @TomaszDziezykNetcentric in https://github.com/Netcentric/vg-volvotrucks-us-rd/pull/22#discussion_r1282842106_

**Comment by Lakshmishri** [comment]
The developer can come up with approach of what can be done and discussed with team for agreement

**Comment by TomaszDziezykNetcentric** [comment]
Proposed solution:
<img width="2061" alt="obraz" src="https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/125962117/42ad7b34-c251-40cf-a503-ccac4df3f353">

The problem appears when the carousel shows at last 2 images (both 100% visible on the screen).
In the solution the width of the carousel is limited to 2.9 of the image width Thanks for that we only show one full image in the center and max ~0.9 of the images on the rigth/left images.

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
