### ISSUE TITLE
Bug - Relaunching modal issues

### ISSUE THREAD

**Issue by DanielaPedrochevd** [Netcentric/vg-volvotrucks-us-rd#288]
**How to reproduce:**

1. Open link -> https://develop--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/tdziezyk/v2/pre-reveal-event-modal
2. Click "Notify me" button, Modal should open with the form. 
3. Complete and submit the form.
4. Close the modal. 
5. Reopen modal by clicking on the "Notify Me" button again. 

**Expected result**

Only one Read policy link should appear and the form should be displayed with the fields empty and displaying the submit and add to calendar buttons. 

![Image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/144998505/b89c43d9-7a8d-4d90-8ded-3c68ae496acd)

**Actual result**

The Read Policy link is duplicated every time you close and reopen the modal, the form is displayed with the previously filled information and omitting the add to calendar button.

![Image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/144998505/83d0d1b7-e569-4270-8c6e-4c40ac1036de)

**Comment by DanielaPedrochevd** [comment]
solved in #296

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
