### ISSUE TITLE
Bug - Social block Visual QA issues

### ISSUE THREAD

**Issue by DanielaPedrochevd** [Netcentric/vg-volvotrucks-us-rd#289]
**How to reproduce**
1. Go to https://develop--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/tdziezyk/v2/pre-reveal-event-modal (or any digital reveal page that contains the social block) 
2. Scroll to the social block

**Expected Result**

On tablet and mobile, text size should be body regular 2 (18px) and spacing between social icons on desktop and tablet should be 40px, and on mobile: 24px

![Image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/144998505/a4478b40-67f3-4e57-8343-1358df83169c)

**Actual Result**
There is a wider spacing and the font is not the same. 

![Image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/144998505/877c7da0-4ab3-440a-ba9c-e6215439318f)

**Comment by DanielaPedrochevd** [comment]
related to #220

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
 as tested on https://289-social-block-qa-issues--vg-volvotrucks-us-rd--netcentric.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/block-library/blocks/v2-social-block&index=0
