### ISSUE TITLE
Bug - Modal Visual QA issues

### ISSUE THREAD

**Issue by DanielaPedrochevd** [Netcentric/vg-volvotrucks-us-rd#290]
**How to reproduce**
1. On **Mobile**, go to -> https://develop--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/tdziezyk/v2/pre-reveal-event-modal (or any digital reveal page that contains the modal) 
2. Open the modal 

**Expected result**
The padding between the closing button of the modal and the title should match and there should be a 32px padding at the bottom of the modal. 

![Image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/144998505/aefb66b5-2c31-4ed6-8735-ee8db62bedba)

![Image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/144998505/cb752ece-9021-46cb-9dfd-7b3dbe55bf96)

**Actual result** 
The padding between the closing button of the modal and the title is bigger than expected and there is no 32px padding at the bottom of the modal. 

![Image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/144998505/664461dc-f340-4499-8a5c-81552ea80b29)

![Image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/144998505/3415f9f8-67b9-4c9f-a37e-1175391ce97d)

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
as tested on https://290-modal-visual-qa-issue--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/tdziezyk/v2/pre-reveal-event-modal
