### ISSUE TITLE
Content task - Social block content task reveal and post reveal page

### ISSUE THREAD

**Issue by DanielaPedrochevd** [Netcentric/vg-volvotrucks-us-rd#294]
**Description** 
Edit the link from the copy page icon in the [reveal](https://develop--vg-volvotrucks-us-rd--netcentric.hlx.page/reveal-event)  or [post reveal ](https://develop--vg-volvotrucks-us-rd--netcentric.hlx.page/post-reveal-event)to copy the current page link (not the LinkedIn link)

**Comment by BeckyMedlin** [comment]
Per @Kannan-CM This has been completed.
