### ISSUE TITLE
Bug - Multiple event calendar file downloading

### ISSUE THREAD

**Issue by DanielaPedrochevd** [Netcentric/vg-volvotrucks-us-rd#296]
**How to reproduce**

1. Go to https://develop--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/tdziezyk/v2/pre-reveal-event-modal or https://develop--vg-volvotrucks-us-rd--netcentric.hlx.page/pre-reveal-event
2. Open the modal
3.  Close modal
4.  Open modal.
5.  Click the "add to calendar" button. - 2 invites downloaded 

**Expected result**
Only one file is downloaded

**Actual result**
Multiple files are downloaded

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
 as tested on https://296-event-invitation--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/tdziezyk/v2/pre-reveal-event-modal
