### ISSUE TITLE
Bug - Content Carousel typography adjustments

### ISSUE THREAD

**Issue by DanielaPedrochevd** [Netcentric/vg-volvotrucks-us-rd#297]
**How to reproduce** 

1. Go to https://develop--vg-volvotrucks-us-rd--netcentric.hlx.page/post-reveal-event
2. Scroll to the Content Carousel

**Expected Result**
Carousel title typography style should use section header, heading 5.5 and carousel image caption typography style should use overline, regular.

**Actual result**
Incorrect title typography style and content carousel image caption typography style.

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
 as tested on https://297-content-carousel--vg-volvotrucks-us-rd--netcentric.hlx.page/block-library/blocks/v2-content-carousel
 
 and with the mention of the following known issues:
 
- Image size is not according to design. This will be picked up in a later issue
- On desktop viewport bigger than 1440px the images don’t continue further to the right
