### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by Lakshmishri** [Netcentric/vg-volvotrucks-us-rd#3]
Implement header based on new designs for all screen sizes. Search functionality is out of scope for this issue (search icon points to the search page).

https://www.figma.com/file/IcqreRKnNYyDVMc28yoOeh/Homepage?type=design&node-id=4271-21750&mode=design&t=7R9SLcKCinr5XmCO-4

- The links will follow the [default/selected/hover state from Volvo Core Design Kit](https://www.figma.com/file/JglsLWtLIgdFru0p8Va2vz/BETA---Volvo-Core-Design-Kit?type=design&node-id=700-29717&mode=design&t=qiy9Hsxnz6BB3jKC-4). The focus state will be the same as the hover state.

### Requirements
- On desktop, an extra link is shown ("Find a dealer" with icon)
- On mobile and tablet, the links are placed in a modal side menu when the user taps the hamburger menu icon

#### Behaviour
- When the header is out of view, and the user scrolls up, the header will appear (sticky). It will be hidden [once the user scrolls down again](https://bootstrap-menu.com/demos/autohide.html).
- 

#### Styling
- The links will follow the [default/selected/hover state from Volvo Core Design Kit](https://www.figma.com/file/JglsLWtLIgdFru0p8Va2vz/BETA---Volvo-Core-Design-Kit?type=design&node-id=700-29717&mode=design&t=qiy9Hsxnz6BB3jKC-4). The focus state will be the same as the hover state.
- Menu items in main navigation are centre-aligned
- On mobile and tablet, the following motion will happen:
  - Appearing:
    - Move sideways into the screen
    - Duration: 450ms
    - Easing: easing-entrance
  - Disappearing:
    - Move sideways out of the screen
    - Duration: 450ms
    - Easing: easing-exit
- When the user has set in their OS they prefer reduced motion, the animations will be disabled

![image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/133873665/8d52dd5a-2865-4881-ad09-c96e19d2196d)

#### Icons
The following [icons](https://www.volvogroup.com/experiencesystem/en/#/brand/615bfcc428c818001105b4e3/61a0de32a7047974164f01dd/622b4b1737a675408d76d87b) should be used:

- Control/Close
- Control/Search
- Navigation/Hamburger Menu
- Navigation/Chevron Down
- Navigation/Chevron Up
- People/User
- Vehicles/Truck NA

#### Open points (relate to a follow up ticket for navigation):
- Burger menu content
- Fold out menu for each navigation item to be defined
- Services and about volvo are not direct links, but trucks and news might be direct links

**Comment by Andrei-Boiangiu** [comment]
confirmed as done
