### ISSUE TITLE
Bug - Post reveal page quote spacing

### ISSUE THREAD

**Issue by DanielaPedrochevd** [Netcentric/vg-volvotrucks-us-rd#301]
**How to reproduce**

1. Go to https://develop--vg-volvotrucks-us-rd--netcentric.hlx.page/post-reveal-event
2. Scroll to the quote block
3. check sizing and spacing

**Expected result**

Spacing between quote and speaker name should be 24px on desktop, 16px on tablet, 8px on mobile. 

**Actual result**

The spacing is different from what was specified in figma.

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed 
 as tested on https://301-quote-spacing--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/tdziezyk/v2/quote
