### ISSUE TITLE
Bug - Content Carousel fading effect

### ISSUE THREAD

**Issue by DanielaPedrochevd** [Netcentric/vg-volvotrucks-us-rd#305]
**How to reproduce**

1.  Go to https://develop--vg-volvotrucks-us-rd--netcentric.hlx.page/
2. Scroll to the content carousel 
3. Go to the mobile and/or tablet viewport

**Expected result**
There is a fading effect. 

![Image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/144998505/9eb5e71b-5e3d-4769-900a-5f7bd0283eb9)

**Actual result**
There is no fading effect. 

![Image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/144998505/52f6c870-1fe4-425b-bfd9-14b3d16228ad)

**Comment by DanielaPedrochevd** [comment]
Dependent on ticket #297 to avoid code issues, will be unblocked once the mentioned ticket is done.

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed 
 as it complies with the design here https://www.figma.com/file/4PrFQO93oPaF721aT3meXj/VNL-Digital-Reveal?type=design&node-id=4929-64357&mode=dev
 
 and as tested on: https://297-content-carousel--vg-volvotrucks-us-rd--netcentric.hlx.page/block-library/blocks/v2-content-carousel
