### ISSUE TITLE
Bug - Major - Mobile - Volvo Trucks Configurator - User is not able to scroll down in landscape view

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [Netcentric/vg-volvotrucks-us-rd#312]
When the Volvo Trucks Configurator is viewed in landscape mode on a Mobile device, the user is not able to scroll down to the section below - only loader with for the “image” is in view

**Steps to reproduce:**
01. Open https://external-app--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/tdziezyk/v2/v2-iframe on a Mobile device and add the correct credentials
02. Rotate device to landscape view
03. Notice that only the loader is in view and user is not able to scroll down to the section below

**Expected result**
User should be able to scroll and correctly view content in landscape view of Mobile

**Actual result**
User is not able to to scroll down below the loader for the “image” in landscape view in Mobile

**Comment by Andrei-Boiangiu** [comment]
#199

**Comment by TomaszDziezykNetcentric** [comment]
It looks like this is the premeditated behaviour.

In the app css I found line that is responsible for hidding the missing part:

```
@media (min-width: 652px) and (max-width: 920px) and (orientation: landscape) and (min-aspect-ratio: 4 / 3) { display: none }
```

This can be fixe by the team responsible for the Truck Configuration.

**Comment by DanielaPedrochevd** [comment]
Closed after last comment.

**Comment by DanielaPedrochevd** [comment]
Closed after last comment.
