### ISSUE TITLE
Key facts alignment incorrect with long titles

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-volvotrucks-us-rd#325]
Expected:
![image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/133873665/056406b5-42c3-48e5-a54f-372848f66094)

Result:
![develop--vg-volvotrucks-us-rd--netcentric hlx page_drafts_vtd_dnqk-pdp (2)](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/133873665/de258606-e8b2-4a06-89aa-3594be4490f1)

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results hence, marking the defect to defect done status:
URL: https://325-key-facts-alignment--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/syb/key-facts

<img width="1792" alt="image" src="https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/125972657/dd9019f9-d764-42c6-a186-29a45cd0f3e6">
