### ISSUE TITLE
Bug: Loading video when using One Trust cookie management acceptance button

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-volvotrucks-us-rd#331]
**Agile requirement**
As a user, when I discard the cookies form the cookie management message aemsites/vg-volvotrucks-us#310 and accept the one trust cookies, the video is played.

**Comment by BeckyMedlin** [comment]
@cogniSyb Please address #330 first.

**Comment by shirin27** [comment]
Kamino cloned this issue to [hlxsites/vg-volvotrucks-us](https://github.com/hlxsites/vg-volvotrucks-us/issues/571)
