### ISSUE TITLE
Rework motion and text container of Trucks lineup

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-volvotrucks-us-rd#36]
As discussed in our meeting with YML, the agency will provide us with guidelines on motion and text container sizing.

The Trucks lineup (#16) will need to be updated once we receive these guidelines.

#### Easing
![image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/133873665/f1f99cd5-bbcf-4bef-9acc-0e76d1c44b17)

#### Tabs
On mobile, the selected model should always be in view. When the user swipes to another truck, the newly selected navigation button should be scrolled into view, with motion applied.

#### Rename block
Rename the 'tabbed-carousel' block to 'truck-lineup' block
- The animation is not applicable to the scroll action

**Comment by BeckyMedlin** [comment]
@manuel-vara @shirin27 Given its priority, Joe and I would like this one actioned in the next sprint. Thank you!

**Comment by Andrei-Boiangiu** [comment]
confirmed as done
