### ISSUE TITLE
Hero

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-volvotrucks-us-rd#41]
Adjust the Hero block to the [new Hero design](https://www.figma.com/file/IcqreRKnNYyDVMc28yoOeh/Homepage?type=design&node-id=1387-17442&mode=design&t=Cm2KlkRhd4ejeM1A-4) and add it to the homepage.

### Requirements
- Background is either an image or an autoplay video (playing for less than 3s)
  - FE will control the length of the video, and stop it after 3s and show the stopped video
- Size is always the available viewport height, without the height of the header
- Text container
  - will have a maximum width (TBD)
  - can be aligned in centre, left (horizontally), [bottom](https://www.figma.com/file/yv0VtHTvMoGPqkv0RAYcVp/PDP?type=design&node-id=3327-41826&mode=design&t=V4GXPIGvkJfr1Y9B-4), or [top left](https://www.volvotrucks.us/trucks/powertrain/i-torque/)
  - contains heading (H1 for the title)
  - can contain text, can be placed either before or after heading (paragraph, < p > tag)
  - to prevent authors from not using an H1 on the hero, we transform any heading they use to H1; in this case, the text will be a paragraph, and the heading (any heading from H2-H6) will be transformed to H1
  - can contain a button, or two. First link should be [primary](https://www.figma.com/file/JglsLWtLIgdFru0p8Va2vz/BETA---Volvo-Core-Design-Kit?node-id=36903%3A110249&mode=dev) button  (dark or light, authors will decide depending on the contrast of the image), next should be [secondary](https://www.figma.com/file/JglsLWtLIgdFru0p8Va2vz/BETA---Volvo-Core-Design-Kit?node-id=36903%3A110301&mode=dev) (dark or light, authors will decide depending on the contrast of the image)
- Scroll indicator ([animated](https://www.figma.com/proto/IcqreRKnNYyDVMc28yoOeh/Homepage?page-id=2%3A17&node-id=1461-18527&scaling=scale-down&starting-point-node-id=325%3A2483&hide-ui=1))

Example of two buttons: https://www.figma.com/file/IcqreRKnNYyDVMc28yoOeh/Homepage?type=design&node-id=870-12300&mode=design&t=Cm2KlkRhd4ejeM1A-4
Example of alignment of two buttons on mobile: https://www.figma.com/file/IcqreRKnNYyDVMc28yoOeh/Homepage?type=design&node-id=875-12929&mode=design&t=Cm2KlkRhd4ejeM1A-4

NOTE:
To be tested with the empty div for the header; header + hero combination to be tested after the header implementation. #3

**Comment by Andrei-Boiangiu** [comment]
_header + hero combination to be tested after the header implementation. https://github.com/Netcentric/vg-volvotrucks-us-rd/issues/3_

keeping this parked in Testing until #3 is ready for testing

**Comment by Andrei-Boiangiu** [comment]
issue retested and can be closed as done

as for header + hero combination in #3  check the comments there
