### ISSUE TITLE
Key facts

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-volvotrucks-us-rd#42]
Adjust existing block with new typography, which will fix #31. We’re adding an image to the block as well. In this case, the alignment of the key facts will be different. 

The content makes use of available space as much as possible
- On mobile and tablet, the facts are [placed below the visual](https://www.figma.com/file/yv0VtHTvMoGPqkv0RAYcVp/PDP?type=design&node-id=1091-22224&mode=design&t=KmUPP5UMoxagXFmW-4)
- When possible, the facts are [placed in one row](https://www.figma.com/file/yv0VtHTvMoGPqkv0RAYcVp/PDP?type=design&node-id=1091-23179&mode=design&t=KmUPP5UMoxagXFmW-4).
- On desktop, the facts are shown [next to the visual](https://www.figma.com/file/yv0VtHTvMoGPqkv0RAYcVp/PDP?type=design&node-id=3781-47910&mode=design&t=KmUPP5UMoxagXFmW-4).

**Technical notes**
- Reuse the same block (Key facts), refactor the component and adjust the typography
- If an image is added, readjust the content to fit the image; ELSE, content should be arranged is today

**Comment by Andrei-Boiangiu** [comment]
reopened for Video thumbnail issue on Safari browser above #125

**Comment by Andrei-Boiangiu** [comment]
Video thumbnail issue above is still present #125

**Comment by Andrei-Boiangiu** [comment]
confirmed as done
