### ISSUE TITLE
Subscribe to newsletter

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-volvotrucks-us-rd#43]
New block, with a [form to subscribe to the newsletter](https://www.figma.com/file/IcqreRKnNYyDVMc28yoOeh/Homepage?type=design&node-id=4656-28990&mode=design&t=jSaNtMqeLOOZQH2P-4). The Pardot form handler will need to be used, which is set up.

### Requirements
- Text
  - On tablet, the text can [run over two lines](https://www.figma.com/file/IcqreRKnNYyDVMc28yoOeh/Homepage?type=design&node-id=915-14350&mode=design&t=HPHnuMiIDDaZ17pQ-4).
  - On mobile, the text will be [above the text field](https://www.figma.com/file/IcqreRKnNYyDVMc28yoOeh/Homepage?type=design&node-id=917-14106&mode=design&t=HPHnuMiIDDaZ17pQ-4).
- Label
  - Floating label (the label "floats" to the top when a selection is inputted)
- Input field
  - Has hover/error/disabled/focused/active states according to the [Core Design Kit](https://www.figma.com/file/JglsLWtLIgdFru0p8Va2vz/BETA---Volvo-Core-Design-Kit?type=design&node-id=602-19045&mode=design&t=lrKtgvHvoVfPzG0Q-4). This should be set up so that the colours change if they are used on a dark background #47 
  - Is set as required:
    - Label will have a character added when 'required' is set ([see prototype](https://volvoexperincesystem.z6.web.core.windows.net/?path=/story/component-text-field--text-field-template&args=type:email;floatingLabel:true;label:Enter+your+email;helperText:;required:true;icon:!undefined&globals=backgrounds.grid:true))
  - Is of type e-mail:
    - To provide a contextual keyboard on some mobile devices
    - Have basic form validation done by the browser
  - ~~Submit button overlays the input field~~
    - ~~Text of button is configurable but hidden accessibly~~
    - ~~arrow-right icon to be used~~
- Submit button
  - On mobile, the button will be placed below the text field
  - Upon submission and receiving a 200 response code, we will show a 'thank you message'
  - Upon submission and receiving a 500 response code, we will show an 'error message'
- Form handler to be used is http://go.pardot.com/l/1038333/2023-09-06/43jv

**Comment by shirin27** [comment]
Forms are to be migrated to Salesforce Pardot; to be implemented with Pardot and not Eloqua.

**Comment by Andrei-Boiangiu** [comment]
back in progress due to the Bug regarding design for Mobile and Tablet view #127

**Comment by Andrei-Boiangiu** [comment]
confirmed as done without the success / error message implemented and the notes from https://github.com/Netcentric/vg-volvotrucks-us-rd/pull/96
