### ISSUE TITLE
V2 Banner block

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-volvotrucks-us-rd#44]
Also known in the design as the [build banner](https://www.figma.com/file/yv0VtHTvMoGPqkv0RAYcVp/PDP?type=design&node-id=2781-33334&mode=design&t=cgkZI6EUlc0gX4XE-4). The current design can be found [just above the footer on the VNR PDP](https://www.volvotrucks.us/trucks/vnr/).

### Requirements
- Full width image
- Heading on top
- Primary button

**Technical solution:**
- Create a new block (**V2 Banner block**) with the design in Figma; this can also be used by editors for the use cases where they were previously using heroes in the middle of the page
- Allow text to be positioned as follows:
  - center
  - left (horizontally) - padding should be in line with what was implemented for the hero
  - bottom - padding should be in line with what was implemented for the hero
  - top left - padding should be in line with what was implemented for the hero
- Account for dark and light theming (based on the contrast of the image, the authors can choose what theming to use)
- Check the hero in terms of background of the text also ( #41 )
- If two buttons are used on the Banner, the first one is primary and the second one is secondary (as it is on the Hero)

**Open point**
- UX: Should we have some text background to ensure the text contrast is AA compliant/readable?
- UX: Should we allow videos as bg for this component?
- UX: Has the heading maps been reviewed with a SEO agency? We saw some things we are not sure they are correct from an SEO perspective, such as an H4 pre-title before an H2

![Image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/135319298/453717c6-a141-4df4-8d42-b05229b6a685)

**Comment by shirin27** [comment]
Decision to adjust current [block](https://www.volvotrucks.us/trucks/vnr/), re-styling it to be full width:



![Image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/135319298/3fcf8b48-4e66-4465-bceb-4701d2353241)

**Comment by ZoeBeykirch** [comment]
Note increasing priority due to additional risk due to existing content block on production.

**Comment by Andrei-Boiangiu** [comment]
confirmed as done as tested per the points above
