### ISSUE TITLE
In-page navigation

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-volvotrucks-us-rd#45]
A redesign of the current subnav block, with an important difference: it links mostly to page fragments. This will be a new block. It’s similar to the [in-page navigation of Mack Trucks](https://github.com/Netcentric/vg-macktrucks-com-rd/issues/26).

### Requirements
- Sections should be given an id in Franklin by content editors
- The sections should be added in the in-page navigation block in Franklin
  - The order of links is necessary
  - Title, like "Powertrain"
  - Link, like "#powertrain"
  - A product name can be defined
- Can contain a small CTA button that links to the Truck Builder ("Build yours" button)
- Part of the overlay on mobile/tablet is a fixed label (Sections), that should be part of Franklin placeholders in order to be translated

#### Behaviour
- Clicking a link will scroll the user to the page fragment, utilising smooth scroll
- Upon clicking a link, we will utilise `history.replaceState()`*
- On mobile and tablet, the navigation will be [hidden behind a toggle](https://www.figma.com/file/yv0VtHTvMoGPqkv0RAYcVp/PDP?type=design&node-id=3393-42192&mode=design&t=tav2YE5FoPisCinb-4)
  - A [custom modal](https://www.figma.com/file/yv0VtHTvMoGPqkv0RAYcVp/PDP?type=design&node-id=3393-42240&mode=design&t=tav2YE5FoPisCinb-4) will be used to allow the user to scroll to a different page fragment
  - The custom modal will disappear once a link is tapped.
- Remains sticky on scroll
  - Sticky position will change when user scrolls up and the header will be shown. See #3
  - On desktop, [the product name will be shown](https://www.figma.com/file/yv0VtHTvMoGPqkv0RAYcVp/PDP?type=design&node-id=3345-42724&mode=design&t=tav2YE5FoPisCinb-4) upon scroll (if it’s defined in the block)
- Utilising intersection observer, the current section in view will be shown as selected in the in-page navigation (see styling)
- Utilising intersection observer, the id of the current section in view will be added to the URL
- On mobile and tablet, the current section in view will be shown as text for the toggle

#### Styling
- The links will follow the [default/selected/hover state from Volvo Core Design Kit](https://www.figma.com/file/JglsLWtLIgdFru0p8Va2vz/BETA---Volvo-Core-Design-Kit?type=design&node-id=700-29717&mode=design&t=qiy9Hsxnz6BB3jKC-4). The focus state will be the same as the hover state.
- The custom modal will have an overlay, black with 60% opacity
- The custom modal will have motion when it’s shown:
  - Appearing:
    - Move upwards into the screen
    - Duration: 450ms
    - Easing: easing-entrance

  - Disappearing:
    - Move downwards out of the screen
    - Duration: 450ms
    - Easing: easing-exit
- When the user has set in their OS they prefer reduced motion, the animations will be disabled

\* By utilising `history.replaceState()`, we ensure that the browser history doesn't grow. When the user navigates or scrolls through the sections, the URL is being replaced. When the browser back button is used, the user will navigate away from the page, rather than navigating through every section they scrolled past.

**Comment by Andrei-Boiangiu** [comment]
reopening ticket with the following bugs and to be retested after fixes
 
 Bug - Major - In-Page Navigation - The active state of a selected Subnavigation menu section link is the wrong color #93
 https://github.com/Netcentric/vg-volvotrucks-us-rd/issues/93
 
 Bug - Major - Mobile view - iPhone - In-Page Navigation - The current selected section from the Subnav menu is not indicated by being bolded in the pop-up menu #94
  https://github.com/Netcentric/vg-volvotrucks-us-rd/issues/94 
  
   Bug - Critical - Mobile view - In-Page Navigation - Selecting a section from the subnavigation menu will not update the Subnavigation header #95
    https://github.com/Netcentric/vg-volvotrucks-us-rd/issues/95

**Comment by Andrei-Boiangiu** [comment]
reopening ticket due to the following Bugs being present / still present

Bug - Major - In-Page Navigation - The active state of a selected Subnavigation menu section link is the wrong color https://github.com/Netcentric/vg-volvotrucks-us-rd/issues/93

Bug - Mobile view - Critical - The Custom modal does not disappear after selecting a link or by clicking the X button #123
https://github.com/Netcentric/vg-volvotrucks-us-rd/issues/123

**Comment by Andrei-Boiangiu** [comment]
confirmed as done **as tested on**
https://develop--vg-volvotrucks-us-rd--netcentric.hlx.page/pdp
