### ISSUE TITLE
FR: Section metadata options: background colour

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-volvotrucks-us-rd#47]
By default, sections (or page fragments) don’t have a background colour defined. On the [PDP](https://www.figma.com/file/yv0VtHTvMoGPqkv0RAYcVp/PDP?type=design&node-id=1091-23111&mode=dev) and [in modals on the PDP](https://www.figma.com/file/yv0VtHTvMoGPqkv0RAYcVp/PDP?type=design&node-id=1741-24323&mode=dev), we can have a dark or [grey background](https://www.figma.com/file/yv0VtHTvMoGPqkv0RAYcVp/PDP?type=design&node-id=3781-47970&mode=dev).

### Requirements
- A section can have a modifier class "grey" or "black"
- Utilising CSS Custom Properties, colours of backgrounds and text will change in components
  - Rename `--c-background-card` to `--card-background`
  - Add `--card-text`
- Tertiary / text buttons will follow the [Core Design Kit](https://www.figma.com/file/JglsLWtLIgdFru0p8Va2vz/BETA---Volvo-Core-Design-Kit?type=design&node-id=535-22166&mode=design&t=7Whg1qSDrRsD8cHz-4), and will always be shown in uppercase.

**Comment by shirin27** [comment]
How would blocks behave against different background colours?
Example: cards always have a light grey background for the text area, what if they are placed on a grey background also?

**Comment by Lakshmishri** [comment]
- If it's just a single block that has background we can create class based on the background colour via styling attribute of section metadata or adding the class using JS
- If there are multiple blocks sharing same background, we can use metadata section [ backgroundSections ---> (block names)], have wrapper for these blocks and add class . 

[Info](https://www.hlx.live/developer/block-collection/section-metadata) about using section metadata.

**Comment by Andrei-Boiangiu** [comment]
confirmed as done
