### ISSUE TITLE
Add legal link to footer

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-volvotrucks-us-rd#50]
> We checked with the IT team, here's the response: We must keep everything according to legal, however, Contact Us and Volvo Shop can go to another area.

- We should add [Do Not Sell or Share My Personal Information](https://www.volvogroup.com/en/tools/privacy/data-subject-rights.html) back to the footer
- The link to switch region (select market) will be put in the footer, as it’s being removed from the header (https://github.com/Netcentric/vg-volvotrucks-us-rd/issues/3)

- [Designs](https://www.figma.com/file/IcqreRKnNYyDVMc28yoOeh/Homepage?type=design&node-id=4152-20617&mode=design&t=62XnRXSWmLicTFq5-0) provided here
- Rename the v2-footer to footer

**Comment by Andrei-Boiangiu** [comment]
confirmed as done
