### ISSUE TITLE
Bug - Major - Trucks Lineup Carousel - Explore button is incorrectly displayed or missing on some of the Trucks from the carousel

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [Netcentric/vg-volvotrucks-us-rd#51]
On the Trucks Lineup Carousel of the Volvo VNR Electric Truck - the Explore button is incorrectly displayed on the 6x2 Tractor slide and is missing from the 6x4 Tractor slide

**Steps to reproduce:**
1. Go to https://16-trucks-lineup--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/laura/
2. Scroll down to the Trucks Lineup Carousel and go to the 6X2 Tractor slide
3. Notice the Explore button / link in the text
4. Go to 6X4 Tractor slide
5. Notice missing Explore button

**Expected result**
Explore button should be correctly displayed and present as per design

**Actual result**
Explore button is not correctly displayed on the VNR Electric 6x2 slide

<img width="1797" alt="image" src="https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/127409602/96438554-e9d3-4665-ac22-09fe1cbaae3a">

and Explore button is missing from the last 6x4 Tractor slide

<img width="1797" alt="image" src="https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/127409602/27631970-fa59-4d31-bfbb-7d3d29931ab1">

**Comment by kesiah** [comment]
@Andrei-Boiangiu this is content issue. Already solved ;P

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
