### ISSUE TITLE
Bug - Major - Mobile view - Trucks Lineup Carousel - Slides from the Trucks Carousel do not have different (front facing) images displayed on the Mobile view

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [Netcentric/vg-volvotrucks-us-rd#52]
On the Mobile view of the Trucks Lineup Carousel block - the last two slides for 6x2 Tractor and 6x4 Tractor do not have the different images with the trucks front facing, the same small images for trucks are displayed

**Steps to reproduce:**
1. Go to https://16-trucks-lineup--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/laura/ on Mobile view
2. Slide through the Trucks Lineup Carousel block
3. Notice the images on the last two Slides

**Expected result**
The slides should have the correct different images of front facing trucks on Mobile and Tablet view

**Actual result**
The last two slides do not have the correct different images of front facing trucsk - smaller versions of the same truck versions are displayed

<img width="382" alt="image" src="https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/127409602/30e014c9-6596-4e54-9e06-5d8fc57b9e95">

<img width="382" alt="image" src="https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/127409602/cde31ea6-5dfa-4406-ba2f-03da9f5e3889">

**Comment by kesiah** [comment]
Also content issue. Should we create the content exactly as in the designs?

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
