### ISSUE TITLE
Bug - Major - Stories carousel - Image not displayed from the second slide of Stories carousel

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [Netcentric/vg-volvotrucks-us-rd#55]
An image from Stories carousel is not correctly displayed.

**Steps to reproduce:**
1. Go to https://14-stories-carousel--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/laura/
2. Scroll down to the Stories carousel and see the second Slide
3. Notice that the image is not correctly displayed

**Expected result**
All images should be correctly displayed

**Actual result**
Image from the second slide on Stories carousel is not correctly displayed

<img width="1758" alt="image" src="https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/127409602/094b67f9-9051-4cf1-93ef-b26defcf6e2c">

**Comment by Andrei-Boiangiu** [comment]
#14

**Comment by kesiah** [comment]
This is a content issue, not related with code.
