### ISSUE TITLE
Bug - Major - Safari - Stories carousel - The Text content on the slide on the left does not fade out on Safari browser

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [Netcentric/vg-volvotrucks-us-rd#56]
When scrolling through the Stories carousel on Safari browser - the text content of the slide of the left does not fade out

**Steps to reproduce:**
1. Open https://14-stories-carousel--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/laura/ on Safari and go down to the Stories carousel block
2. Scroll throught the Stories carousel
3. Notice that the text of the left slide does not fade out correctly on the slide to the left or when scrolling right to left

**Expected result**
Text content should fade in or out correctly upon entry or exit

**Actual result**
On Safari browser, the Text content does not fade out correctly on the slide to the left or when scrolling right to left

<img width="1683" alt="image" src="https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/127409602/cd5df56d-eb59-4583-822c-427fb37c9607">

**Comment by BeckyMedlin** [comment]
@DanielaPedrochevd @Gonzalo-CG Please update the status on this ticket. Is it still needed?

**Comment by Andrei-Boiangiu** [comment]
this issue is still present on Safari
 as tested on both
 https://14-stories-carousel--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/laura/
 and
 https://develop--vg-volvotrucks-us-rd--netcentric.hlx.page

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
