### ISSUE TITLE
Bug - Stories carousel - Remove The name of the author in desktop / tablet view of the Stories carousel

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [Netcentric/vg-volvotrucks-us-rd#57]
Remove the author name in desktop / tablet team similar to mobile view

**Actual result**
Author name is not displayed in the text content section of the Stories carousel on Mobile view

<img width="400" alt="image" src="https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/127409602/c6867e46-ef8b-4c7f-94a8-029d3165f68d">

**Comment by Andrei-Boiangiu** [comment]
#14

**Comment by kesiah** [comment]
Which is the design we should follow? Home launch or Pre-launch? I see some inconsistenies :(

@shirin27 what should we do?

<img width="245" alt="image" src="https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/3090999/2b64c204-7f7c-4f8a-8a75-3e025acbc295">

**Comment by kesiah** [comment]
We can close it, because this is a change request done by the client and opened in a new issue: https://github.com/Netcentric/vg-volvotrucks-us-rd/issues/78
