### ISSUE TITLE
Quote Block

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-volvotrucks-us-rd#65]
Design in context:
https://www.figma.com/file/4PrFQO93oPaF721aT3meXj/VNL-Digital-Reveal?type=design&node-id=2824-133704&mode=dev

### Requirements
- Content
  - Quote
  - Source
- [Card background colour and text colour will change](https://www.figma.com/file/Id3nd9kbfh8TpS1SfWhrW2/Volvo-Component-Library?type=design&node-id=961-7340&mode=design&t=JIUFKjUpG3QKeBPx-4) according to section background #47
- On tablet and mobile, the block is full-width
- On desktop, the block is as wide as the regular content container (1170px)

### To be determined
- [x] How do we name this block? - Quote block
- [x] Max width for the text TBD

**Comment by BeckyMedlin** [comment]
@cogniSyb We have a similar component on the SuperTruck2 page: https://www.volvotrucks.us/innovation/supertruck2/ 
Can we reuse it instead of building new? 
![MicrosoftTeams-image (15)](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/142249558/c6f4fab7-364e-4e92-ba9e-12713bd77800)

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
