### ISSUE TITLE
Countdown in hero

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-volvotrucks-us-rd#66]
The hero will need to [contain a countdown](https://www.figma.com/file/4PrFQO93oPaF721aT3meXj/VNL-Digital-Reveal?type=design&node-id=2744-118604&mode=dev) during the pre-reveal phase.

An example can be found on https://main--theplayers--hlxsites.hlx.live/ and its code at https://github.com/hlxsites/theplayers/blob/main/blocks/header/header.js#L93

### Requirements
- The countdown will be shown above the title in the hero
- All digits need to be shown on the same line
- The digits need to be using `font-feature-settings: 'tnum';` to maintain alignment
- Granularity will be days/hours/minutes/seconds
- All numbers will have two digits. So if needed, we’ll have a leading zero. For example: "04" or "20"
- When one of the items will have a value of one, the singular word will be shown. For example: "01 day" versus "42 days"
- A date should be set by a content editor
- A new "bold" font should be included. 
- The hero should include a new button that is displayed only in the reveal and post-reveal phase. When the user clicks on it, the event video modal is opened. -> Design Agency working in the design change as per the last comment. 

### To be determined
- [x] What will be shown once the countdown is over? - **Assumption**: show the countdown with 0, force reload until new content should be available, hide part of the content
- [x] Timezone to be confirmed. - **Assumption**: only support EST timezone, US date/time format
 - Date: 2020-05-12
 - Time: 23:50
- [x] How do we name this block? - Not a block, but a variation of the Hero: **Hero (countdown)**

### Technical hints
**Proposal**: Add the countdown in the section metadata for the hero (with the time and the date) and only load the countdown block when this date or time metadata is on the page.

**Comment by BeckyMedlin** [comment]
@Gonzalo-CG Please move to backlog for now.

**Comment by taimurCognizant** [comment]
Some assumption:
 - When the countdown runs out then all the values would be 00.  
 - If the user is visiting the page while the event is being live or have been expired then the countdown will not be displayed.
 - The date format should be in ISO 8601 format. E.g '2023-11-20T14:00:00.000Z'. Editors can add this date in the section meta data.

**Comment by DanielaPedrochevd** [comment]
Design Question: 

The Hero Component in the[ reveal](https://www.figma.com/file/4PrFQO93oPaF721aT3meXj/VNL-Digital-Reveal?type=design&node-id=2744-122064&mode=dev) phase should include this "play" button however, in the [post-reveal](https://www.figma.com/file/4PrFQO93oPaF721aT3meXj/VNL-Digital-Reveal?type=design&node-id=2767-127088&mode=dev) phase, we have this link which reads "watch  the VNL Review". Is there any major functional difference between them, or can we decide on having one? This would diminish some development efforts. If so, which one?



![Image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/144998505/358a1d32-6c17-47f2-9390-abd012c894fd)



![Image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/144998505/4b457262-445c-4b92-b743-bdeb1531a07f)

@ozzy-krishnan

**Comment by Andrei-Boiangiu** [comment]
confirmed as done 
  as tested on
  https://66-countdown-in-hero--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/taimur/hero
  https://66-countdown-in-hero--vg-volvotrucks-us-rd--netcentric.hlx.page/reveal-event
https://66-countdown-in-hero--vg-volvotrucks-us-rd--netcentric.hlx.page/post-reveal-event
