### ISSUE TITLE
Social block

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-volvotrucks-us-rd#67]
On the event page, a block with social media icons will be shown. Depending on the phase, the links will do something different.

- https://www.figma.com/file/4PrFQO93oPaF721aT3meXj/VNL-Digital-Reveal?type=design&node-id=2744-118606&mode=dev
- https://www.figma.com/file/4PrFQO93oPaF721aT3meXj/VNL-Digital-Reveal?type=design&node-id=2744-122066&mode=dev

### Requirements
- Reuse the social media icons from the footer
- Links to social media platforms OR share to social media URL
- Clicking the link icon will copy the share link to the user's clipboard
  - A [tooltip](https://www.volvogroup.com/experiencesystem/en/#/brand/615bfcc428c818001105b4e3/61a0de32a7047974164f01dd/6231c4f237a675408d8c3492) will be shown to inform the user once they clicked
  - The tooltip implementation should be as simple as possible
- Provide a documentation on how the URL to share the page to a social platform should look
  - ex. https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fyourwebsite.com

### To be determined
- [x] How do we name this block? - Social block
- [ ] New ticket to enhance the tooltip to have it up to Volvo Core Design Kit standards

**Comment by Andrei-Boiangiu** [comment]
confirmed as done 
 as tested on https://76-modal--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/tdziezyk/v2/modal
