### ISSUE TITLE
Implement event notifications

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-volvotrucks-us-rd#68]
**Agile Requirement**

On the event page, during the pre-reveal phase, a user can sign up for event notifications. The [form will be shown below the hero](https://www.figma.com/file/4PrFQO93oPaF721aT3meXj/VNL-Digital-Reveal?type=design&node-id=2744-118510&mode=dev).

**Description**

Create a new personalized form Block that will allow users to complete the different fields, the dtata will be sent to a Form Handler that will provide a success (confirmation) message validating their suscription to the event or an error message. 

**Acceptance Criteria**

- Triggered by “notify me” button on [event page](https://www.figma.com/file/4PrFQO93oPaF721aT3meXj/VNL-Digital-Reveal?type=design&node-id=2713-88904&mode=dev) -> clicking on notify me acts as an anchor link to the form below on the page
- ~~Modal does not obscure navigation~~
- Form with following elements:
- Title "Be the first to see the all-new Volvo VNL"
- Subtitle "Sign up here to be notified about the digital reveal on January 23rd at 1 PM EST"
  - Text field “First name”
  - Text field “Last name”
  - Text field “ZIP code”
  - Text field of type e-mail “E-mail”
  - Checkbox to confirm agreement to Privacy Policy -> If the user does not check it, a notification will be displayed ~~the "notify me button will remain inactive"~~ 
  - Link to Privacy Policy will be placed in a paragraph below checkbox, for accessibility purposes, upon click, they will be open in a separate tab. 
  - Submit button “Notify me”, connected to Pardot endpoint (Form Handler).  
    - Success and error handling similar to #43 
- Form details
  - Styling will be done in #43 (floating labels), but the alignment of the form fields needs to be created:
    - On mobile: all form items below each other
    - On tablet:
      - two columns with a 16px gutter
      - vertical gutter between form fields and checkbox is 40px
    - On desktop:
      - two columns with a 20px gutter
      - vertical gutter between form fields and checkbox is 48px
  - All form items are required:
    - Which will add an asterisk to the labels, see #43 
    - Basic client-side form validation is being done by the browser
    - Form validation is implemented in the client's side. 
- “Add event to calendar” triggers user’s default calendar client, see #72

### To be determined
- [x] Figure out whether we switch from modal to linking to a section on the same page
- [x] Form validation from Pardot.
- [x] Error state after submitting form

**Comment by BeckyMedlin** [comment]
Decision: The modal is not necessary. Need to create a web form (vs iFrame).

**Comment by DanielaPedrochevd** [comment]
Because this form is so personalized and need the custom validation message, we need more flexibility so we decided to develop a custom form.

**Comment by DanielaPedrochevd** [comment]
Technical details:

**Comment by manuel-vara** [comment]
FYI @ryanropero , can you implement a form handler (with same settings success, error and kiosk/data entry mode as subscribe to newsletter form handler) mapping to these fields below, please?


![Image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/116451851/0f09de0c-d9c4-4967-a9c7-9222629fbbd5)

Please let us know the form handler url and the names you have used over this thread once is created to start testing.

**Comment by manuel-vara** [comment]
Form handler: https://go.pardot.com/l/1038333/2023-11-27/8hmb
Field names:


![Image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/116451851/b8d02789-60f7-4c94-a732-58bbcd964206)


Where `marketing_consent` can be true | false
+honeypot field added in the forms block.

**Comment by Andrei-Boiangiu** [comment]
confirmed as done
