### ISSUE TITLE
Content Carousel

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-volvotrucks-us-rd#70]
In the modal for driving environment, you can find this carousel. It consists of a content container (header + paragraph), and a few images with a caption text below them.

https://www.figma.com/file/yv0VtHTvMoGPqkv0RAYcVp/PDP?type=design&node-id=1812-24921&mode=dev

### Requirements
- Buttons with previous/next arrows are used to navigate
  - When the start or the end of the carousel is reached, the respective button will be shown as inactive/disabled
- On desktop, the content container is shown next to the images
- On mobile/tablet the content container is shown on the top 
- Content remains static 
- Images will have a caption
- Animation is similar to [Promises](https://github.com/Netcentric/vg-volvotrucks-us-rd/issues/11)
- The component uses scroll-snap, and its behaviour/implementation is the same as [#11](https://github.com/Netcentric/vg-volvotrucks-us-rd/issues/11) on mobile 

### To be determined
- [ ] How do we name this block?

**Comment by DanielaPedrochevd** [comment]
related to #78

**Comment by Andrei-Boiangiu** [comment]
confirmed as done 
 as tested on https://70-content-carousel--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/lakshmi/content-carousel
