### ISSUE TITLE
Calendar invite

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-volvotrucks-us-rd#72]
**Agile Requirement**
Provide a way to the user to add the event to their calendar. A link should be provided to download the event invite.

**Description**
Develop a button where, by clicking, an [ICS file](https://www.webdavsystem.com/server/creating_caldav_carddav/calendar_ics_file_structure/) with the correct event details should be generated with JavaScript to generate a Blob (binary large object)allows users to add the event to their calendar by downloading the ICS file to their calendar.

<img width="1208" alt="Captura de pantalla 2023-11-16 a las 9 37 53" src="https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/144998505/6771982f-e385-4ecc-bebf-501229f69d60">

**Acceptance Criteria**
- Clicking the add to calendar button will download the ICS file directly. 
- An [ICS file](https://www.webdavsystem.com/server/creating_caldav_carddav/calendar_ics_file_structure/) with the correct event details should be generated with JavaScript to generate a Blob (binary large object)
- The ICS file should include:
  - PRODID: generated by application e.g. "-//Volvo Trucks//Volvo Trucks US website//EN"
  - UID: unique identifier of the file; consisting of timestamp, unique string, domain (e.g. "20231210T120000Z-123456@example.com")
  - SUMMARY: event title
  - DTSTART and DTEND: start and end date in ISO 8601 format (e.g. "20231210T120000Z")
  - DESCRIPTION: containing the URL to join the event
  - LOCATION: "online"
- All of the above attributes should be editable by content editors in the html in the **metadata block** or in a JSON file besides LOCATION and PRODID and UID which we should generate. 

#### Behaviour
- When the user clicks the "Add to Calendar" link, the ICS file should be downloaded to their device

**Comment by DanielaPedrochevd** [comment]
After SRB Meeting we will be going for Apple's approach where we only have 1 button and the ICS file is downloaded.

**Comment by Andrei-Boiangiu** [comment]
confirmed as done
 as tested on https://68-event-notifications--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/tdziezyk/v2/pardot-test
