### ISSUE TITLE
Header mega dropdown / navigation

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-volvotrucks-us-rd#75]
Extend the header #3 with a mega dropdown as on the current website. No design has been provided, minimal design changes to be done.

![Screenshot 2023-09-12 at 10 31 55](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/133873665/a34d6f39-df83-4379-820d-295cb67f9b9f)

### Requirements
- The same menu items as on current navigation need to be included
- Less (complex) code than current state

#### Behaviour on mobile/tablet
- The mega-dropdown is a group of accordions. Menu items act like an accordion and will show their navigation items upon tapping

#### Styling on mobile/tablet
- The links will follow the [default/selected/hover state from Volvo Core Design Kit](https://www.figma.com/file/JglsLWtLIgdFru0p8Va2vz/BETA---Volvo-Core-Design-Kit?type=design&node-id=700-29717&mode=design&t=qiy9Hsxnz6BB3jKC-4).

![image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/133873665/8d52dd5a-2865-4881-ad09-c96e19d2196d)

#### Behaviour on desktop
- Once a menu item is tapped in the header, the sub-navigation will appear and show the corresponding items
- Clicking outside the mega dropdown will close the mega dropdown

#### Styling on desktop
- The main menu item will have an active state upon clicking, which is the same as the current pressed state
- The mega dropdown will overlap the in-page navigation #45
- ~~The mega dropdown will remain sticky when opened~~
- The margins, typography and colours will be aligned with redesign
- The lists are of equal width, but don’t necessarily fill the whole dropdown (maybe create a proper minimum width?)
- Trucks dropdown to be made smaller in size (now the user has to scroll to see Powertrain)
  - Trucks grouped together (on one line?)

Example solution direction:
![Screen Shot 2023-09-11 at 10 15 56](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/133873665/f799fac4-688d-4fe5-82db-6eb6840df0a6)

**Comment by Andrei-Boiangiu** [comment]
confirmed as done
