### ISSUE TITLE
FR: Add the possibility to have link and button stylings coexisting

### ISSUE THREAD

**Issue by shirin27** [Netcentric/vg-volvotrucks-us-rd#79]
### Problem statement:

At the moment, all links are considered as buttons in styling; we need to have a way to differentiate, based on the word content, between buttons and links.

### Requirements
- Give the authors a way of defining if a button is really a button or a link

### Reference links:

- [Buttons styling](https://www.figma.com/file/JglsLWtLIgdFru0p8Va2vz/BETA---Volvo-Core-Design-Kit?type=design&node-id=280-25971&mode=design&t=1YaYRZqfiLEc7Cdl-0)

- [Links styling](https://www.figma.com/file/JglsLWtLIgdFru0p8Va2vz/BETA---Volvo-Core-Design-Kit?type=design&node-id=235-37224&mode=design&t=1YaYRZqfiLEc7Cdl-0)

**Comment by Gonzalo-CG** [comment]
Won't fix. Franklin provides OOTB ways to differentiate.
