### ISSUE TITLE
Teaser cards

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-volvotrucks-us-rd#88]
[Visual adjustment](https://www.figma.com/file/yv0VtHTvMoGPqkv0RAYcVp/PDP?type=design&node-id=6610-7770&mode=dev) of existing teaser cards. We will create a new block with v2- prefix. Related to #11; refactoring required.

### Requirements
- Style changes: sizing, typography, colours, background, rounded corners
- ~~On mobile, the cards will be scrollable~~
- When the amount of cards is odd, the last item will be as wide as the container on tablet/desktop
- Colours change [according to context](https://www.figma.com/file/Id3nd9kbfh8TpS1SfWhrW2/Volvo-Component-Library?type=design&node-id=398-8212&mode=design&t=ynTTAjqhDm7J7Zly-4)

**Comment by Andrei-Boiangiu** [comment]
confirmed as done
