### ISSUE TITLE
Enhancement: replace font files and add WOFF2

### ISSUE THREAD

**Issue by cogniSyb** [Netcentric/vg-volvotrucks-us-rd#9]
To increase performance, we can use the WOFF2 variant of the web font Volvo Novum.

The font files can be downloaded from the [typography page of the Volvo Core Design Kit](https://www.volvogroup.com/experiencesystem/en/#/brand/615bfcc428c818001105b4e3/61652f5f8ea937001135220e/61975e6d69102a0012754ffe).

We should include only WOFF and WOFF2, given the [support of browsers](https://caniuse.com/?search=woff). Especially as the font file is of a different version, we should apply visual regression testing.

**Comment by Andrei-Boiangiu** [comment]
Merge blocked at the moment
will park this here and resume it when the PR will be merged

in the meanwhile: screenshots to be used in assistance for visual regression  testing have been added in the following wiki space: 
[Visual regression testing for Volvo Redesign](https://projects.netcentric.biz/wiki/display/VOLVOFN/Visual+regression+testing+for+Volvo+Redesign)
