### ISSUE TITLE
Bug - Major - Header - The space between the Header links is too large

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [Netcentric/vg-volvotrucks-us-rd#92]
The space between Trucks, Services etc buttons from the Header is too large as specified in the design

**Steps to reproduce:**
1. Open https://3-header--vg-volvotrucks-us-rd--netcentric.hlx.page/#
2. Open the figma design https://www.figma.com/file/IcqreRKnNYyDVMc28yoOeh/Homepage?type=design&node-id=4152-20617&mode=design&t=2RMRXt161AAJXa4j-0
3. Notice the difference in distance between the URLs from the figma design vs the Header from the PR branch

**Expected result**
The space between the items in the header should be 32px

**Actual result**
The space between the items in the header is greater than 32px and greater than what it is marked in the figma design

![image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/127409602/c4e1150d-2cf5-4c52-a99a-0879e308e3d5)

**Comment by Andrei-Boiangiu** [comment]
#3

**Comment by BeckyMedlin** [comment]
@Andrei-Boiangiu Please add a screenshot that displays both together to explain the problem clearly.

**Comment by Andrei-Boiangiu** [comment]
@BeckyMedlin I generally avoid adding screenshots of figma designs here but I will add one below
  
  first half is the figma design and second half is the PR env 
  
![image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/127409602/b6be7656-c9d8-4ff3-84c5-741988e5207a)

**Comment by BeckyMedlin** [comment]
Thank you for confirming and clarifying the issue, @Andrei-Boiangiu.

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed as tested on develop branch
 
 https://develop--vg-volvotrucks-us-rd--netcentric.hlx.page/
