### ISSUE TITLE
Bug - Major - In-Page Navigation - The active state of a selected Subnavigation menu section link is the wrong color

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [Netcentric/vg-volvotrucks-us-rd#93]
When selecting a subnavigation section link - it has the regular color of  #53565A instead of the selected color of #141414 
 
 **Steps to reproduce:**
 1. Open https://45-in-page-navigation--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/laura/inpage-navigation#section-3-3 and click on a Subnavigation link
 2. See the font color for an active selected Tab in the Subnavigation https://www.figma.com/file/JglsLWtLIgdFru0p8Va2vz/BETA---Volvo-Core-Design-Kit?type=design&node-id=290-32262&mode=design&t=QF6eNnWspfT0J3sS-0
 3. Notice that the selected Subnavigation link has the regular color of  #53565A instead of the color of #141414 
 
 **Expected result**
 The color of the selected Subnavigation link should be #141414 
 
 **Actual result**
 The color of the selected Subnavigation link should be the regular color of #53565A
 
 
<img width="1021" alt="image" src="https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/127409602/4265bb60-e098-4efa-937e-3133dfad7de8">

**Comment by Andrei-Boiangiu** [comment]
#45

**Comment by Andrei-Boiangiu** [comment]
Issue is still present as tested on both
 https://93-in-page-nav-active-state--vg-volvotrucks-us-rd--netcentric.hlx.page/
 and https://95-bug-inpagenavigation--vg-volvotrucks-us-rd--netcentric.hlx.page/pdp

**Comment by markovukiceviccn** [comment]
This is ready to be re-tested.

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
